name: Assignment 1
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t assignment1:latest .

    - name: Run Docker container
      run: docker run -d --name assignment1_container assignment1:latest

    - name: Show running Docker container
      run: docker ps

    - name: Stop Docker container
      run: docker stop assignment1_container